// <auto-generated />
namespace MVC_Role_Resource.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SecRoletablemodified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SecRoletablemodified));
        
        string IMigrationMetadata.Id
        {
            get { return "201901210840532_SecRole table modified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
