// <auto-generated />
namespace MVC_Role_Resource.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SecResourceandSecResourcePermissiontablesmodified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SecResourceandSecResourcePermissiontablesmodified));
        
        string IMigrationMetadata.Id
        {
            get { return "201901230132282_SecResource and SecResourcePermission tables modified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
