// <auto-generated />
namespace MVC_Role_Resource.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SecUsertablemodified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SecUsertablemodified));
        
        string IMigrationMetadata.Id
        {
            get { return "201901211137431_SecUser table modified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
